### ISSUE TITLE
fix null pointer exception (2 smaller channels stuck) 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/ytsync#110]
```INFO[2260] blockchain.db uploaded to S3
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0xc000916488 addr=0x4ffbac pc=0xf04133]
goroutine 1 [running]:
github.com/lbryio/lbry.go/v2/extras/jsonrpc.(*Claim).GetStreamSizeByMagic(0xc0005a4000, 0x0, 0x0, 0x0)
        /home/travis/gopath/pkg/mod/github.com/lbryio/lbry.go/v2@v2.7.2-0.20210412222918-ed51ece75c3d/extras/jsonrpc/daemon_types.go:382 +0x93
github.com/lbryio/ytsync/v5/manager.(*Sync).updateRemoteDB(0xc0005ad720, 0xc000bf8000, 0xa, 0xb, 0x1bfef30, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/lbryio/ytsync/manager/ytsync.go:520 +0x507
github.com/lbryio/ytsync/v5/manager.(*Sync).checkIntegrity(0xc0005ad720, 0x0, 0x0)
        /home/travis/gopath/src/github.com/lbryio/ytsync/manager/ytsync.go:648 +0x266
github.com/lbryio/ytsync/v5/manager.(*Sync).doSync(0xc0005ad720, 0xc0000b8010, 0xc003cdd6a0)
        /home/travis/gopath/src/github.com/lbryio/ytsync/manager/ytsync.go:701 +0x2ba
github.com/lbryio/ytsync/v5/manager.(*Sync).FullCycle(0xc0005ad720, 0x0, 0x0)
        /home/travis/gopath/src/github.com/lbryio/ytsync/manager/ytsync.go:185 +0x8cf
github.com/lbryio/ytsync/v5/manager.(*SyncManager).Start(0xc000132dd0, 0xc000132dd0, 0xc00003e02e)
        /home/travis/gopath/src/github.com/lbryio/ytsync/manager/manager.go:126 +0x6ae
main.ytSync(0xc0005a4f00, 0xc0005aad90, 0x0, 0x7)
        /home/travis/gopath/src/github.com/lbryio/ytsync/main.go:167 +0x59c
github.com/spf13/cobra.(*Command).execute(0xc0005a4f00, 0xc0000c2010, 0x7, 0x7, 0xc0005a4f00, 0xc0000c2010)
        /home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0005a4f00, 0x1bfeda0, 0x12028d2, 0xa)
        /home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
        /home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /home/travis/gopath/src/github.com/lbryio/ytsync/main.go:65 +0x8d3```

**Comment by nikooo777** [comment]
fixed the broken function which solves this
