### ISSUE TITLE
upgrade to python3 latest ytdl on all servers

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/ytsync#96]
Some may have python2 version which fails on some videos. 

Also, noticed this new error which we need to see if it's been fixed on latest version: ```
RRO[0483] Skipping video (gJJEVXctsns): *exec.ExitError youtube-dlc youtube-dlc --skip-download --print-json https://www.youtube.com/watch?v=gJJEVXctsns --cookies cookies.txt --source-address 2604:6800:233:940:: [[20842] Failed to execute script __main__
Traceback (most recent call last):
  File "youtube_dlc/__main__.py", line 19, in <module>
  File "youtube_dlc/__init__.py", line 487, in main
  File "youtube_dlc/__init__.py", line 477, in _real_main
  File "youtube_dlc/YoutubeDL.py", line 2104, in download
  File "youtube_dlc/YoutubeDL.py", line 830, in extract_info
  File "youtube_dlc/extractor/common.py", line 532, in extract
  File "youtube_dlc/extractor/youtube.py", line 1817, in _real_extract
  File "/usr/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
]: exit status 255```

**Comment by tzarebczan** [comment]
this was done
